[package]
name = "line_input"
version = "0.1.0"
authors = ["Jennifer Glauche <meow@rust.kittenme.ws>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

console = "0.9.0"
